import './globals.css'
import { Inter, Montserrat, Oswald } from 'next/font/google'
import Header from '@/components/header'
import Footer from '@/components/footer'


const inter = Inter({ subsets: ['latin'] })
export const oswald = Oswald({
  subsets: ["latin"],
});

export const montserrat = Montserrat({
  subsets : ['latin']
})


// export const metadata =
//   {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
//   }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>

        {children}

        <Footer />
      </body>
    </html>
  )
}
